version: "3"
services:
  postgres:
    ports:
      - 5433:5432
    image: postgres
    environment:
      - POSTGRES_PASSWORD=junepoon
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=junepoon
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=fastapi
      - SECRET_KEY=fogjoiurhgl34hj5ghj435hjk435h43j5lk
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres-db:
