"""25/5/66

Revision ID: c5790033eaa3
Revises: 
Create Date: 2023-05-25 01:39:23.050723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5790033eaa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dividend', 'stocks', ['symbol'], ['symbol'])
    op.create_foreign_key(None, 'transactions', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'turnover', 'stocks', ['symbol'], ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turnover', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'dividend', type_='foreignkey')
    # ### end Alembic commands ###
